CREATE TABLE person (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(50) NOT NULL,
 password bytea NOT NULL,
 description varchar(500),
 last_publish timestamp with time zone
);

CREATE SEQUENCE person_sequence start 1000 increment 1;

CREATE TABLE followed_following (
 followed int references person(id),
 following int references person(id),
 constraint id PRIMARY KEY (followed, following)
);

CREATE TABLE publication (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 parent int,
 datetime timestamp with time zone NOT NULL,
 text varchar(150) NOT NULL,
 author int references person(id)
);

INSERT INTO person(name, password, description, last_publish) VALUES ('cesar', '123123', 'just a normal guy', null);
INSERT INTO person(name, password, description, last_publish) VALUES ('kaiser', '123123', 'special k', null);
commit;

drop table followed_following;
drop table person;